/// Flutter icons BlutvIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BlutvIcon
///      fonts:
///       - asset: fonts/BlutvIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BlutvIcon {
  BlutvIcon._();

  static const _kFontFam = 'BlutvIcon';
  static const String? _kFontPkg = null;

  static const IconData blutvicon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blutv_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kids = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
